# Generated by Django 5.1 on 2024-08-31 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBSItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='CoilTubing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('year_of_import', models.IntegerField(verbose_name='سال واردات')),
                ('length_of_reel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='طول لوله مغزی')),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تناژ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(db_index=True, verbose_name='تاریخ پایان')),
                ('total_value', models.DecimalField(decimal_places=0, max_digits=16, verbose_name='ارزش کل')),
                ('total_value_euro', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ارزش کل (یورو)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('syear', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال شروع')),
                ('smonth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه شروع')),
                ('sday', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز شروع')),
                ('sdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ شروع')),
                ('sdatenumber', models.IntegerField(blank=True, null=True, verbose_name='تاریخ شماری شروع')),
                ('eyear', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال پایان')),
                ('emonth', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه پایان')),
                ('eday', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز پایان')),
                ('edate', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ پایان')),
                ('edatenumber', models.IntegerField(blank=True, null=True, verbose_name='تاریخ شماری پایان')),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع قرارداد')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='شخص رابط')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='نماد')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='CoilTubingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('coil_tubing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.coiltubing', verbose_name='لوله مغزی')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coil_tubings', to='core.contract', verbose_name='قرارداد')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('contact_person', models.CharField(max_length=100, verbose_name='شخص رابط')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.contractor', verbose_name='پیمانکار'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.contracttype', verbose_name='نوع قرارداد'),
        ),
        migrations.CreateModel(
            name='CBSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='قیمت واحد')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbs_items', to='core.contract', verbose_name='قرارداد')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='واحد')),
            ],
        ),
    ]
