# Generated by Django 5.1 on 2024-09-01 03:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='user',
        ),
        migrations.AddField(
            model_name='contractor',
            name='users',
            field=models.ManyToManyField(related_name='contractors', to=settings.AUTH_USER_MODEL, verbose_name='کاربران'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('approved', 'Approved'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال شروع')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه شروع')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز شروع')),
                ('pdate', models.CharField(blank=True, max_length=15, null=True, verbose_name='تاریخ شروع')),
                ('datenumber', models.IntegerField(blank=True, null=True, verbose_name='تاریخ شماری شروع')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('coil_tubing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.coiltubing')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reports', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.contract')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='core.report')),
            ],
        ),
    ]
