# Generated by Django 5.1 on 2024-08-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coiltubing',
            name='date_of_manufacturing',
        ),
        migrations.RemoveField(
            model_name='coiltubing',
            name='date_of_purchase',
        ),
    ]
