# Generated by Django 5.1 on 2024-09-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contractor_user_contractor_users_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه\u200cها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False, verbose_name='انتخاب شده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='سرویس')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.report', verbose_name='گزارش')),
                ('subcontractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcontractor', verbose_name='پیمانکار فرعی')),
            ],
            options={
                'verbose_name': 'استفاده از دستگاه',
                'verbose_name_plural': 'استفاده\u200cهای دستگاه',
                'ordering': ['-created'],
            },
        ),
    ]
