# Generated by Django 5.0.7 on 2024-08-30 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_coiltubing_date_of_manufacturing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbsitem',
            name='cbs_item_type',
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbs_items', to='core.contract', verbose_name='قرارداد'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit', verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='cbsitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='cbsitemtype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='cbsitemtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='cbsitemtype',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='length_of_reel',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='طول لوله مغزی'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='tonnage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تناژ'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='coiltubing',
            name='year_of_import',
            field=models.IntegerField(verbose_name='سال واردات'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='coil_tubing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.coiltubing', verbose_name='لوله مغزی'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coil_tubings', to='core.contract', verbose_name='قرارداد'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='created',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='end_date',
            field=models.DateField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='coiltubingcontract',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.contracttype', verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.contractor', verbose_name='پیمانکار'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='edate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='edatenumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='تاریخ شماری پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='eday',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='emonth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='eyear',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sdate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sdatenumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='تاریخ شماری شروع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sday',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز شروع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='smonth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه شروع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='syear',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال شروع'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_value',
            field=models.DecimalField(decimal_places=0, max_digits=16, verbose_name='ارزش کل'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_value_euro',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ارزش کل (یورو)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='symbol',
            field=models.CharField(max_length=10, unique=True, verbose_name='نماد'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
