# Generated by Django 5.1 on 2024-09-01 07:10

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_deviceusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'عملیات',
                'verbose_name_plural': 'عملیات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(db_index=True, verbose_name='زمان شروع')),
                ('end_time', models.TimeField(db_index=True, verbose_name='زمان پایان')),
                ('duration', models.DurationField(db_index=True, verbose_name='مدت زمان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز')),
                ('pdate', models.CharField(blank=True, max_length=15, null=True, verbose_name='تاریخ')),
                ('datenumber', models.IntegerField(blank=True, null=True, verbose_name='تاریخ شماری')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.report', verbose_name='گزارش')),
                ('responsible', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_activities', to='core.category', verbose_name='مسئول')),
                ('status', mptt.fields.TreeForeignKey(limit_choices_to={'level': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.category', verbose_name='وضعیت')),
                ('waiting_reason', mptt.fields.TreeForeignKey(blank=True, limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waiting_reason_activities', to='core.category', verbose_name='دلیل انتظار')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.job', verbose_name='عملیات')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
            },
        ),
    ]
